--Autor: Maciej Zbierowski
-- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
--   at:        2017-01-11 18:24:01 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

CREATE TABLE adres_nauczyciela
  (
    id_adres      INTEGER NOT NULL ,
    ulica         VARCHAR2 (50) NOT NULL ,
    nr_ulicy      NUMBER NOT NULL ,
    nr_mieszkania NUMBER NOT NULL ,
    kod_pocztowy  VARCHAR2 (10) NOT NULL ,
    miasto        VARCHAR2 (40) NOT NULL
  ) ;
COMMENT ON TABLE adres_nauczyciela
IS
  'adres nauczyciela table' ;
ALTER TABLE adres_nauczyciela ADD CONSTRAINT adres_nauczyciela_PK PRIMARY KEY ( id_adres ) ;


CREATE TABLE adres_studenta
  (
    id_adres      INTEGER NOT NULL ,
    ulica         VARCHAR2 (50) NOT NULL ,
    nr_ulicy      NUMBER NOT NULL ,
    nr_mieszkania NUMBER NOT NULL ,
    kod_pocztowy  VARCHAR2 (7) NOT NULL ,
    miasto        VARCHAR2 (50) NOT NULL
  ) ;
COMMENT ON TABLE adres_studenta
IS
  'adrees studenta table' ;
ALTER TABLE adres_studenta ADD CONSTRAINT adres_studenta_PK PRIMARY KEY ( id_adres ) ;


CREATE TABLE egzamin
  (
    id_egzamin     INTEGER NOT NULL ,
    data_egzaminu  DATE NOT NULL ,
    ilosc_punktow  NUMBER NOT NULL ,
    id_przedmiot   INTEGER NOT NULL ,
    id_egzaminator INTEGER NOT NULL
  ) ;
COMMENT ON TABLE egzamin
IS
  'egzamin table' ;
ALTER TABLE egzamin ADD CONSTRAINT egzamin_PK PRIMARY KEY ( id_egzamin ) ;


CREATE TABLE egzaminator
  (
    id_egzaminator INTEGER NOT NULL ,
    id_nauczyciel  INTEGER NOT NULL
  ) ;
COMMENT ON TABLE egzaminator
IS
  'egzaminator table' ;
ALTER TABLE egzaminator ADD CONSTRAINT egzaminator_PK PRIMARY KEY ( id_egzaminator ) ;


CREATE TABLE grupa
  (
    id_grupa      INTEGER NOT NULL ,
    nazwa         VARCHAR2 (2) NOT NULL ,
    limit_osob    NUMBER NOT NULL ,
    id_rok        INTEGER NOT NULL ,
    id_nauczyciel INTEGER NOT NULL
  ) ;
COMMENT ON TABLE grupa
IS
  'grupa table' ;
ALTER TABLE grupa ADD CONSTRAINT grupa_PK PRIMARY KEY ( id_grupa ) ;


CREATE TABLE kierunek
  (
    id_kierunek INTEGER NOT NULL ,
    nazwa       VARCHAR2 (30) NOT NULL ,
    tryb        CHAR (2) DEFAULT 's' NOT NULL ,
    id_wydzial  INTEGER NOT NULL
  ) ;
COMMENT ON TABLE kierunek
IS
  'kierunek table' ;
ALTER TABLE kierunek ADD CONSTRAINT kierunek_PK PRIMARY KEY ( id_kierunek ) ;
ALTER TABLE kierunek ADD CONSTRAINT nazwa UNIQUE ( nazwa ) ;


CREATE TABLE konkurs
  (
    id_konkurs       INTEGER NOT NULL ,
    nazwa            VARCHAR2 (30) NOT NULL ,
    data             DATE NOT NULL ,
    wysokosc_nagrody NUMBER DEFAULT 0 NOT NULL ,
    id_nauczyciel    INTEGER NOT NULL ,
    id_student       INTEGER NOT NULL
  ) ;
COMMENT ON TABLE konkurs
IS
  'konkurs table' ;
ALTER TABLE konkurs ADD CONSTRAINT konkurs_PK PRIMARY KEY ( id_konkurs ) ;


CREATE TABLE lekcja
  (
    id_lekcja     INTEGER NOT NULL ,
    temat         VARCHAR2 (30) NOT NULL ,
    id_nauczyciel INTEGER NOT NULL
  ) ;
COMMENT ON TABLE lekcja
IS
  'lekcja table' ;
ALTER TABLE lekcja ADD CONSTRAINT lekcja_PK PRIMARY KEY ( id_lekcja ) ;


CREATE TABLE nauczyciel
  (
    id_nauczyciel     INTEGER NOT NULL ,
    imie              VARCHAR2 (30) NOT NULL ,
    nazwisko          VARCHAR2 (40) NOT NULL ,
    data_urodzenia    DATE NOT NULL ,
    data_zatrudnienia DATE NOT NULL ,
    pesel             VARCHAR2(12) NOT NULL,
    id_adres          INTEGER NOT NULL,
    czy_awans          CHAR(1) NOT NULL
  ) ;
COMMENT ON TABLE nauczyciel
IS
  'nauczyciel table' ;
ALTER TABLE nauczyciel ADD CONSTRAINT nauczyciel_PK PRIMARY KEY ( id_nauczyciel ) ;

CREATE TABLE ocena
  (
    id_ocena        INTEGER NOT NULL ,
    czy_semestralna CHAR (1) NOT NULL ,
    wartosc         NUMBER NOT NULL ,
    opis            VARCHAR2 (15) NOT NULL ,
    id_student      INTEGER NOT NULL ,
    id_przedmiot    INTEGER NOT NULL
  ) ;
COMMENT ON TABLE ocena
IS
  'ocena table' ;
ALTER TABLE ocena ADD CONSTRAINT ocena_PK PRIMARY KEY ( id_ocena ) ;


CREATE TABLE odpowiedz_do_pytania
  (
    id_odpowiedz INTEGER NOT NULL ,
    tresc        VARCHAR2 (50) NOT NULL ,
    czyPoprawne  CHAR (1) NOT NULL
  ) ;
COMMENT ON TABLE odpowiedz_do_pytania
IS
  'odpowiedz table' ;
ALTER TABLE odpowiedz_do_pytania ADD CONSTRAINT odpowiedz_do_pytania_PK PRIMARY KEY ( id_odpowiedz ) ;


CREATE TABLE przedmiot
  (
    id_przedmiot  INTEGER NOT NULL ,
    nazwa         VARCHAR2 (50) NOT NULL ,
    ilosc_godzin  NUMBER NOT NULL ,
    id_student    INTEGER NOT NULL ,
    id_nauczyciel INTEGER NOT NULL
  ) ;
COMMENT ON TABLE przedmiot
IS
  'przedmiot table' ;
ALTER TABLE przedmiot ADD CONSTRAINT przedmiot_PK PRIMARY KEY ( id_przedmiot ) ;
ALTER TABLE przedmiot ADD CONSTRAINT nazwav2 UNIQUE ( nazwa ) ;


CREATE TABLE pytanie_egzaminacyjne
  (
    id_pytanie   INTEGER NOT NULL ,
    tresc        VARCHAR2 (30) NOT NULL ,
    punkty       NUMBER NOT NULL ,
    id_egzamin   INTEGER NOT NULL ,
    id_odpowiedz INTEGER NOT NULL
  ) ;
COMMENT ON TABLE pytanie_egzaminacyjne
IS
  'pytanie egzaminacyjne table' ;
ALTER TABLE pytanie_egzaminacyjne ADD CONSTRAINT pytanie_egzaminacyjne_PK PRIMARY KEY ( id_pytanie ) ;


CREATE TABLE repeta
  (
    id_repeta    INTEGER NOT NULL ,
    cena         NUMBER DEFAULT 0 NOT NULL ,
    id_student   INTEGER NOT NULL ,
    id_przedmiot INTEGER NOT NULL
  ) ;
COMMENT ON TABLE repeta
IS
  'repeta table' ;
ALTER TABLE repeta ADD CONSTRAINT repeta_PK PRIMARY KEY ( id_repeta ) ;


CREATE TABLE rok
  (
    id_rok      INTEGER NOT NULL ,
    numer       NUMBER NOT NULL ,
    id_kierunek INTEGER NOT NULL
  ) ;
COMMENT ON TABLE rok
IS
  'rok table' ;
ALTER TABLE rok ADD CONSTRAINT rok_PK PRIMARY KEY ( id_rok ) ;


CREATE TABLE student
  (
    id_student     INTEGER NOT NULL ,
    imie           VARCHAR2 (30) NOT NULL ,
    nazwisko       VARCHAR2 (40) NOT NULL ,
    data_urodzenia DATE NOT NULL ,
    pesel          VARCHAR2 (12) NOT NULL ,
    srednia        NUMBER DEFAULT 0 NOT NULL ,
    id_grupa       INTEGER NOT NULL ,
    id_adres       INTEGER NOT NULL
  ) ;
COMMENT ON TABLE student
IS
  'student table' ;
ALTER TABLE student ADD CONSTRAINT student_PK PRIMARY KEY ( id_student ) ;


CREATE TABLE stypendium
  (
    id_stypendium INTEGER NOT NULL ,
    kwota         NUMBER NOT NULL ,
    id_student    INTEGER NOT NULL
  ) ;
COMMENT ON TABLE stypendium
IS
  'stypendium table' ;
ALTER TABLE stypendium ADD CONSTRAINT stypendium_PK PRIMARY KEY ( id_stypendium ) ;


CREATE TABLE warunek
  (
    id_warunek   INTEGER NOT NULL ,
    cena         NUMBER DEFAULT 0 NOT NULL ,
    id_student   INTEGER NOT NULL ,
    id_przedmiot INTEGER NOT NULL
  ) ;
COMMENT ON TABLE warunek
IS
  'warunek table' ;
ALTER TABLE warunek ADD CONSTRAINT warunek_PK PRIMARY KEY ( id_warunek ) ;


CREATE TABLE wydzial
  (
    id_wydzial      INTEGER NOT NULL ,
    nazwa           VARCHAR2 (30) NOT NULL ,
    ilosc_kierunkow NUMBER NOT NULL
  ) ;
COMMENT ON TABLE wydzial
IS
  'wydzial table' ;
ALTER TABLE wydzial ADD CONSTRAINT wydzial_PK PRIMARY KEY ( id_wydzial ) ;
ALTER TABLE wydzial ADD CONSTRAINT nazwav1 UNIQUE ( nazwa ) ;


CREATE TABLE zadanie_konkursowe
  (
    id_zadanie    INTEGER NOT NULL ,
    tresc         VARCHAR2 (30) NOT NULL ,
    ilosc_punktow NUMBER NOT NULL ,
    id_konkurs    INTEGER NOT NULL
  ) ;
COMMENT ON TABLE zadanie_konkursowe
IS
  'zadanie konkursowe table' ;
ALTER TABLE zadanie_konkursowe ADD CONSTRAINT zadanie_konkursowe_PK PRIMARY KEY ( id_zadanie ) ;


ALTER TABLE egzamin ADD CONSTRAINT egzamin_egzaminator_FK FOREIGN KEY ( id_egzaminator ) REFERENCES egzaminator ( id_egzaminator ) ;

ALTER TABLE egzamin ADD CONSTRAINT egzamin_przedmiot_FK FOREIGN KEY ( id_przedmiot ) REFERENCES przedmiot ( id_przedmiot ) ;

ALTER TABLE egzaminator ADD CONSTRAINT egzaminator_nauczyciel_FK FOREIGN KEY ( id_nauczyciel ) REFERENCES nauczyciel ( id_nauczyciel ) ;

ALTER TABLE grupa ADD CONSTRAINT grupa_nauczyciel_FK FOREIGN KEY ( id_nauczyciel ) REFERENCES nauczyciel ( id_nauczyciel ) ;

ALTER TABLE grupa ADD CONSTRAINT grupa_rok_FK FOREIGN KEY ( id_rok ) REFERENCES rok ( id_rok ) ;

ALTER TABLE kierunek ADD CONSTRAINT kierunek_wydzial_FK FOREIGN KEY ( id_wydzial ) REFERENCES wydzial ( id_wydzial ) ;

ALTER TABLE konkurs ADD CONSTRAINT konkurs_nauczyciel_FK FOREIGN KEY ( id_nauczyciel ) REFERENCES nauczyciel ( id_nauczyciel ) ;

ALTER TABLE konkurs ADD CONSTRAINT konkurs_student_FK FOREIGN KEY ( id_student ) REFERENCES student ( id_student ) ;

ALTER TABLE lekcja ADD CONSTRAINT lekcja_nauczyciel_FK FOREIGN KEY ( id_nauczyciel ) REFERENCES nauczyciel ( id_nauczyciel ) ;

ALTER TABLE nauczyciel ADD CONSTRAINT nauczyciel_adres_FK FOREIGN KEY ( id_adres ) REFERENCES adres_nauczyciela ( id_adres ) ;

ALTER TABLE ocena ADD CONSTRAINT ocena_przedmiot_FK FOREIGN KEY ( id_przedmiot ) REFERENCES przedmiot ( id_przedmiot ) ;

ALTER TABLE ocena ADD CONSTRAINT ocena_student_FK FOREIGN KEY ( id_student ) REFERENCES student ( id_student ) ;

ALTER TABLE przedmiot ADD CONSTRAINT przedmiot_nauczyciel_FK FOREIGN KEY ( id_nauczyciel ) REFERENCES nauczyciel ( id_nauczyciel ) ;

ALTER TABLE przedmiot ADD CONSTRAINT przedmiot_student_FK FOREIGN KEY ( id_student ) REFERENCES student ( id_student ) ;

ALTER TABLE pytanie_egzaminacyjne ADD CONSTRAINT pytanie_egzamin_FK FOREIGN KEY ( id_egzamin ) REFERENCES egzamin ( id_egzamin ) ;

ALTER TABLE pytanie_egzaminacyjne ADD CONSTRAINT pytanie_odpowiedz_FK FOREIGN KEY ( id_odpowiedz ) REFERENCES odpowiedz_do_pytania ( id_odpowiedz ) ;

ALTER TABLE repeta ADD CONSTRAINT repeta_przedmiot_FK FOREIGN KEY ( id_przedmiot ) REFERENCES przedmiot ( id_przedmiot ) ;

ALTER TABLE repeta ADD CONSTRAINT repeta_student_FK FOREIGN KEY ( id_student ) REFERENCES student ( id_student ) ;

ALTER TABLE rok ADD CONSTRAINT rok_kierunek_FK FOREIGN KEY ( id_kierunek ) REFERENCES kierunek ( id_kierunek ) ;

ALTER TABLE student ADD CONSTRAINT student_adres_studenta_FK FOREIGN KEY ( id_adres ) REFERENCES adres_studenta ( id_adres ) ;

ALTER TABLE student ADD CONSTRAINT student_grupa_FK FOREIGN KEY ( id_grupa ) REFERENCES grupa ( id_grupa ) ;

ALTER TABLE stypendium ADD CONSTRAINT stypendium_student_FK FOREIGN KEY ( id_student ) REFERENCES student ( id_student ) ;

ALTER TABLE warunek ADD CONSTRAINT warunek_przedmiot_FK FOREIGN KEY ( id_przedmiot ) REFERENCES przedmiot ( id_przedmiot ) ;

ALTER TABLE warunek ADD CONSTRAINT warunek_student_FK FOREIGN KEY ( id_student ) REFERENCES student ( id_student ) ;

ALTER TABLE zadanie_konkursowe ADD CONSTRAINT zadanie_konkursowe_konkurs_FK FOREIGN KEY ( id_konkurs ) REFERENCES konkurs ( id_konkurs ) ;

CREATE SEQUENCE adres_nauczyciela_id_adres_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER adres_nauczyciela_id_adres_TRG BEFORE
  INSERT ON adres_nauczyciela FOR EACH ROW WHEN (NEW.id_adres IS NULL) BEGIN :NEW.id_adres := adres_nauczyciela_id_adres_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE adres_studenta_id_adres_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER adres_studenta_id_adres_TRG BEFORE
  INSERT ON adres_studenta FOR EACH ROW WHEN (NEW.id_adres IS NULL) BEGIN :NEW.id_adres := adres_studenta_id_adres_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE egzamin_id_egzamin_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER egzamin_id_egzamin_TRG BEFORE
  INSERT ON egzamin FOR EACH ROW WHEN (NEW.id_egzamin IS NULL) BEGIN :NEW.id_egzamin := egzamin_id_egzamin_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE egzaminator_id_egzaminator_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER egzaminator_id_egzaminator_TRG BEFORE
  INSERT ON egzaminator FOR EACH ROW WHEN (NEW.id_egzaminator IS NULL) BEGIN :NEW.id_egzaminator := egzaminator_id_egzaminator_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE grupa_id_grupa_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER grupa_id_grupa_TRG BEFORE
  INSERT ON grupa FOR EACH ROW WHEN (NEW.id_grupa IS NULL) BEGIN :NEW.id_grupa := grupa_id_grupa_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE kierunek_id_kierunek_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER kierunek_id_kierunek_TRG BEFORE
  INSERT ON kierunek FOR EACH ROW WHEN (NEW.id_kierunek IS NULL) BEGIN :NEW.id_kierunek := kierunek_id_kierunek_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE konkurs_id_konkurs_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER konkurs_id_konkurs_TRG BEFORE
  INSERT ON konkurs FOR EACH ROW WHEN (NEW.id_konkurs IS NULL) BEGIN :NEW.id_konkurs := konkurs_id_konkurs_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE lekcja_id_lekcja_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER lekcja_id_lekcja_TRG BEFORE
  INSERT ON lekcja FOR EACH ROW WHEN (NEW.id_lekcja IS NULL) BEGIN :NEW.id_lekcja := lekcja_id_lekcja_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE nauczyciel_id_nauczyciel_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER nauczyciel_id_nauczyciel_TRG BEFORE
  INSERT ON nauczyciel FOR EACH ROW WHEN (NEW.id_nauczyciel IS NULL) BEGIN :NEW.id_nauczyciel := nauczyciel_id_nauczyciel_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE ocena_id_ocena_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER ocena_id_ocena_TRG BEFORE
  INSERT ON ocena FOR EACH ROW WHEN (NEW.id_ocena IS NULL) BEGIN :NEW.id_ocena := ocena_id_ocena_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE odpowiedz_do_pytania_id_odpowi START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER odpowiedz_do_pytania_id_odpowi BEFORE
  INSERT ON odpowiedz_do_pytania FOR EACH ROW WHEN (NEW.id_odpowiedz IS NULL) BEGIN :NEW.id_odpowiedz := odpowiedz_do_pytania_id_odpowi.NEXTVAL;
END;
/

CREATE SEQUENCE przedmiot_id_przedmiot_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER przedmiot_id_przedmiot_TRG BEFORE
  INSERT ON przedmiot FOR EACH ROW WHEN (NEW.id_przedmiot IS NULL) BEGIN :NEW.id_przedmiot := przedmiot_id_przedmiot_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE pytanie_egzaminacyjne_id_pytan START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER pytanie_egzaminacyjne_id_pytan BEFORE
  INSERT ON pytanie_egzaminacyjne FOR EACH ROW WHEN (NEW.id_pytanie IS NULL) BEGIN :NEW.id_pytanie := pytanie_egzaminacyjne_id_pytan.NEXTVAL;
END;
/

CREATE SEQUENCE repeta_id_repeta_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER repeta_id_repeta_TRG BEFORE
  INSERT ON repeta FOR EACH ROW WHEN (NEW.id_repeta IS NULL) BEGIN :NEW.id_repeta := repeta_id_repeta_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE rok_id_rok_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER rok_id_rok_TRG BEFORE
  INSERT ON rok FOR EACH ROW WHEN (NEW.id_rok IS NULL) BEGIN :NEW.id_rok := rok_id_rok_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE student_id_student_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER student_id_student_TRG BEFORE
  INSERT ON student FOR EACH ROW WHEN (NEW.id_student IS NULL) BEGIN :NEW.id_student := student_id_student_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE stypendium_id_stypendium_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER stypendium_id_stypendium_TRG BEFORE
  INSERT ON stypendium FOR EACH ROW WHEN (NEW.id_stypendium IS NULL) BEGIN :NEW.id_stypendium := stypendium_id_stypendium_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE warunek_id_warunek_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER warunek_id_warunek_TRG BEFORE
  INSERT ON warunek FOR EACH ROW WHEN (NEW.id_warunek IS NULL) BEGIN :NEW.id_warunek := warunek_id_warunek_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE wydzial_id_wydzial_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER wydzial_id_wydzial_TRG BEFORE
  INSERT ON wydzial FOR EACH ROW WHEN (NEW.id_wydzial IS NULL) BEGIN :NEW.id_wydzial := wydzial_id_wydzial_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE zadanie_konkursowe_id_zadanie START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER zadanie_konkursowe_id_zadanie BEFORE
  INSERT ON zadanie_konkursowe FOR EACH ROW WHEN (NEW.id_zadanie IS NULL) BEGIN :NEW.id_zadanie := zadanie_konkursowe_id_zadanie.NEXTVAL;
END;
/
